apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: leader-worker-set
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable-v1.0
  installPlanApproval: Manual
  name: leader-worker-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.startingCSV }}

