apiVersion: v2
name: lws-operator
description: Chart to deploy Leader Worker Set (LWS) operator for OpenShift AI
version: 0.1.0
dependencies:
  - name: helper-status-checker
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    version: 4.4.3
