apiVersion: v2
name: devspaces-operator
description: Helm chart for deploying Red Hat OpenShift Dev Spaces Operator
type: application
version: 0.1.13
appVersion: "3.15"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: ~4.4.1
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
