apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: keycloak-backstage
    app.kubernetes.io/instance: keycloak-backstage
    app.kubernetes.io/name: keycloak-backstage
  name: keycloak-backstage
spec:
  instances: 1
  hostname:
    hostname: keycloak-{{ .Values.namespace }}.{{ .Values.clusterDomain | default "apps.example.com" }}
  http:
    tlsSecret: keycloak-tls-secret
