
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: "og-{{ .Values.namespace }}"
spec:
  targetNamespaces:
    - {{ .Values.namespace }}
  upgradeStrategy: Default
