apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ $.Values.subscription.name }}
spec:
  channel: {{ $.Values.subscription.channel }}
  installPlanApproval: {{ $.Values.subscription.installPlanApproval }}
  name: {{ $.Values.subscription.name }}
  source: {{ $.Values.subscription.source }}
  sourceNamespace: {{ $.Values.subscription.sourceNamespace }}
  startingCSV: {{ $.Values.subscription.startingCSV }}
