{{- if .Values.gatewayAuthPolicy.enabled }}
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: gateway-auth-policy
  namespace: {{ .Values.gateway.namespace }}
  labels:
    app.kubernetes.io/part-of: models-as-a-service
    app.kubernetes.io/component: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
  rules:
    metadata:
      # Enriching identity metadata with a proper subscription tier based on user groups
      matchedTier:
        http:
          url: http://maas-api.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.service.port }}/v1/tiers/lookup
          contentType: application/json
          method: POST
          body:
            expression: |-
              { "groups": auth.identity.user.groups }
        cache:
          key:
            selector: auth.identity.user.username
          ttl: 300
    authentication:
      service-accounts:
        kubernetesTokenReview:
          audiences:
            - maas-default-gateway-sa
            {{- if .Values.authPolicy.customAudience }}
            - {{ .Values.authPolicy.customAudience }}
            {{- end }}
        defaults:
          # token normalization - https://docs.kuadrant.io/1.2.x/authorino/docs/user-guides/token-normalization/
          # full username: system:serviceaccount:<ns>:<name>
          userid:
            expression: |
              auth.identity.user.username.split(":")[3]
        cache:
          key:
            selector: context.request.http.headers.authorization.@case:lower
          ttl: 600
    authorization:
      tier-access:
        cache:
          key:
            selector: "{auth.identity.user.username}:{request.path}"
          ttl: 60
        kubernetesSubjectAccessReview:
          user:
            expression: auth.identity.user.username
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              value: llminferenceservices
            namespace:
              expression: |
                request.path.split("/")[1]
            name:
              expression: |
                request.path.split("/")[2]
            verb:
              value: post
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  expression: auth.identity.userid
                tier:
                  expression: auth.metadata.matchedTier["tier"]
{{- end }}

