{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-api
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: models-as-a-service
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
{{- end }}

