apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
stringData:
  GITHUB_APP_ID: "{{ .Values.github.appId }}"
  GITHUB_CLIENT_ID: "{{ .Values.github.clientId }}"
  GITHUB_CLIENT_SECRET: "{{ .Values.github.clientSecret }}"
  GITHUB_WEBHOOK_SECRET: "{{ .Values.github.webhookSecret }}"
  GITHUB_PRIVATE_KEY: |
{{ .Values.github.privateKey | indent 4 }}

