{{- if .Values.lightspeed.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: lightspeed-postgres-info
  namespace: {{ .Values.lightspeed.postgres.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
type: Opaque
stringData:
  user: {{ .Values.lightspeed.postgres.user | default "postgres" }}
  password: {{ .Values.lightspeed.postgres.password | default "postgres" }}
  db-name: {{ .Values.lightspeed.postgres.dbName | default "lightspeed" }}
{{- end }}


