{{- if .Values.lightspeed.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: lightspeed-stack
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  lightspeed-stack.yaml: |
    name: "lightspeed-core-stack"
    service:
      host: 0.0.0.0
      port: 8080
      auth_enabled: false
      workers: 1
      color_log: true
      access_log: true
    llama_stack:
      use_as_library_client: false
      url: http://localhost:8321
    user_data_collection:
      feedback_enabled: true
      feedback_storage: "/tmp/data/feedback"
    authentication:
      module: "noop"
    conversation_cache:
      type: "sqlite"
      sqlite:
        db_path: "/tmp/cache.db"
    mcp_servers:
      - name: mcp-integration-tools
        provider_id: "model-context-protocol"
        url: "http://{{ .Release.Name }}-backstage.{{ .Values.namespace }}.svc.cluster.local:7007/api/mcp-actions/v1"
{{- end }}


