{{- if .Values.lightspeed.postgres.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.lightspeed.postgres.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}


