{{- if .Values.lightspeed.enabled }}
---
# Secret in lightspeed-postgres namespace
apiVersion: v1
kind: Secret
metadata:
  name: lightspeed-postgres-info
  namespace: {{ .Values.lightspeed.postgres.namespace }}
type: Opaque
stringData:
  namespace: {{ .Values.lightspeed.postgres.namespace | quote }}
  user: {{ .Values.lightspeed.postgres.user | quote }}
  password: {{ .Values.lightspeed.postgres.password | quote }}
  db-name: {{ .Values.lightspeed.postgres.dbName | quote }}
---
# Secret in backstage namespace
apiVersion: v1
kind: Secret
metadata:
  name: lightspeed-postgres-info
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  namespace: {{ .Values.lightspeed.postgres.namespace | quote }}
  user: {{ .Values.lightspeed.postgres.user | quote }}
  password: {{ .Values.lightspeed.postgres.password | quote }}
  db-name: {{ .Values.lightspeed.postgres.dbName | quote }}
{{- end }}


