{{- if .Values.lightspeed.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  VLLM_URL: {{ .Values.lightspeed.vllmUrl | quote }}
  VLLM_API_KEY: {{ .Values.lightspeed.vllmApiKey | default "" | quote }}
  VALIDATION_PROVIDER: {{ .Values.lightspeed.validationProvider | default "vllm" | quote }}
  VALIDATION_MODEL_NAME: {{ .Values.lightspeed.validationModelName | quote }}
{{- end }}
