{{- if .Values.quayPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: redhat-gpte-devhub-pull-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
{{ .Values.quayPullSecret | indent 4 }}
{{- end }}


