{{- if .Values.quayPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: redhat-gpte-devhub-pull-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.quayPullSecret | b64enc }}
{{- end }}


