apiVersion: v2
name: nvidia-gpu-operator
description: Helm chart for deploying NVIDIA GPU Operator
type: application
version: 0.2.19
appVersion: "1.0"
dependencies:
  - name: helper-status-checker
    version: 4.3.7
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled

