dependencies:
  - name: helper-status-checker
    version: 4.4.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-operator
    version: 1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
name: rhacs-operator
version: 0.1.9
apiVersion: v2
description: Chart to deploy the central acs operator and supporting components
