---
# ManagedClusterSetBinding - Allows openshift-gitops namespace to access clusters
# Note: The 'global' ManagedClusterSet already exists in ACM by default
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Delete=false
spec:
  clusterSet: global

