---
# Placement to select all spoke clusters
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-spoke-clusters
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: acm
              operator: In
              values:
                - spoke
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 100
      decisionGroups:
        - groupName: "spoke-clusters"
          groupClusterSelector:
            labelSelector:
              matchLabels: {}

