apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscription.name }}
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | quote }}
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  {{- if .Values.subscription.startingCSV }}
  startingCSV: {{ .Values.subscription.startingCSV }}
  {{- end }}

