apiVersion: v2
name: kiali-operator
description: Helm chart for deploying Red Hat OpenShift Kiali Operator
type: application
version: 0.2.13
appVersion: "1.73"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: 4.4.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
