apiVersion: v2
name: serverless-operator
description: Helm chart for deploying Red Hat OpenShift Serverless Operator
type: application
version: 0.2.12
appVersion: "1.34"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
