{{- if .Values.openshiftAI.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.openshiftAI.gateway.name | default "openshift-ai-inference" }}
  namespace: {{ .Values.openshiftAI.gateway.namespace | default "openshift-ingress" }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.openshiftAI.gateway.syncwave | default "5" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gatewayClassName: {{ .Values.openshiftAI.gateway.gatewayClassName | default "openshift-default" }}
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  infrastructure:
    labels:
      serving.kserve.io/gateway: kserve-ingress-gateway
{{- end }}

