apiVersion: v2
name: rhdh-helm
description: Master chart to deploy developer hub
version: 1.7.9
home: https://github.com/rosa-hcp-dedicated-vpc/helm-repository
dependencies:
  - name: redhat-developer-hub
    version: 9.7.3
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
maintainers:
  - name: Paul Foster
    email: pafoster@redhat.com
    url: https://github.com/rosa-hcp-dedicated-vpc
sources:
  - https://github.com/rosa-hcp-dedicated-vpc/helm-repository
keywords:
  - redhat-developer-hub
  - backstage
  - openshift
