apiVersion: v2
name: virtualization-operator
description: Helm chart for deploying OpenShift Virtualization operator
type: application
version: 0.2.1
appVersion: "4.16"
dependencies:
  - name: helper-status-checker
    version: 4.4.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
