apiVersion: v2
name: rhbk-operator
description: A Helm chart to deploy Red Hat Build of Keycloak (RHBK) operator for Janus-IDP-Demo on Kubernetes
type: application

version: 0.2.2
appVersion: 26.4.2-opr.1
dependencies:
  - name: helper-status-checker
    version: 4.4.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
  