namespace: rhbk-operator
clientSecret: "holder"
clusterDomain: "holder"
subscription:
  channel: stable
  installPlanApproval: Manual
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "holder"
realm:
  identityProviders:
    - alias: GitHub
      providerId: github
      syncMode: IMPORT
client:
  redirectUri:
  - holder


helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: rhbk-operator
      subscriptionName: rhbk-operator
      namespace:
        name: keycloak-operator
      serviceAccount:
        name: "keycloak-status-checker"
 